# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'review_list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReviewListItem(object):
    def setupUi(self, ReviewListItem):
        ReviewListItem.setObjectName("ReviewListItem")
        ReviewListItem.resize(640, 462)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ReviewListItem)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalWidget_controls = QtWidgets.QWidget(ReviewListItem)
        self.horizontalWidget_controls.setObjectName("horizontalWidget_controls")
        self.horizontalLayout_controls = QtWidgets.QHBoxLayout(self.horizontalWidget_controls)
        self.horizontalLayout_controls.setObjectName("horizontalLayout_controls")
        self.button_edit = QtWidgets.QPushButton(self.horizontalWidget_controls)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout_controls.addWidget(self.button_edit)
        self.button_remove = QtWidgets.QPushButton(self.horizontalWidget_controls)
        self.button_remove.setObjectName("button_remove")
        self.horizontalLayout_controls.addWidget(self.button_remove)
        self.verticalLayout_2.addWidget(self.horizontalWidget_controls)
        self.label_title = QtWidgets.QLabel(ReviewListItem)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.title_value = QtWidgets.QLabel(ReviewListItem)
        self.title_value.setObjectName("title_value")
        self.verticalLayout_2.addWidget(self.title_value)
        self.label_date = QtWidgets.QLabel(ReviewListItem)
        self.label_date.setObjectName("label_date")
        self.verticalLayout_2.addWidget(self.label_date)
        self.date_value = QtWidgets.QLabel(ReviewListItem)
        self.date_value.setObjectName("date_value")
        self.verticalLayout_2.addWidget(self.date_value)
        self.label_review = QtWidgets.QLabel(ReviewListItem)
        self.label_review.setObjectName("label_review")
        self.verticalLayout_2.addWidget(self.label_review)
        self.review_value = QtWidgets.QLabel(ReviewListItem)
        self.review_value.setObjectName("review_value")
        self.verticalLayout_2.addWidget(self.review_value)

        self.retranslateUi(ReviewListItem)
        QtCore.QMetaObject.connectSlotsByName(ReviewListItem)

    def retranslateUi(self, ReviewListItem):
        _translate = QtCore.QCoreApplication.translate
        ReviewListItem.setWindowTitle(_translate("ReviewListItem", "Form"))
        self.button_edit.setText(_translate("ReviewListItem", "Edit"))
        self.button_remove.setText(_translate("ReviewListItem", "Remove"))
        self.label_title.setText(_translate("ReviewListItem", "Title"))
        self.title_value.setText(_translate("ReviewListItem", "TextLabel"))
        self.label_date.setText(_translate("ReviewListItem", "Date"))
        self.date_value.setText(_translate("ReviewListItem", "TextLabel"))
        self.label_review.setText(_translate("ReviewListItem", "Review"))
        self.review_value.setText(_translate("ReviewListItem", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReviewListItem = QtWidgets.QWidget()
    ui = Ui_ReviewListItem()
    ui.setupUi(ReviewListItem)
    ReviewListItem.show()
    sys.exit(app.exec_())
