# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageRegister(object):
    def setupUi(self, PageRegister):
        PageRegister.setObjectName("PageRegister")
        PageRegister.resize(614, 632)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PageRegister.sizePolicy().hasHeightForWidth())
        PageRegister.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PageRegister)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.register_label = QtWidgets.QLabel(PageRegister)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        self.register_label.setFont(font)
        self.register_label.setObjectName("register_label")
        self.verticalLayout_2.addWidget(self.register_label)
        self.label_username = QtWidgets.QLabel(PageRegister)
        self.label_username.setObjectName("label_username")
        self.verticalLayout_2.addWidget(self.label_username)
        self.register_Username = QtWidgets.QLineEdit(PageRegister)
        self.register_Username.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    height: 40px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.register_Username.setObjectName("register_Username")
        self.verticalLayout_2.addWidget(self.register_Username)
        self.label_password = QtWidgets.QLabel(PageRegister)
        self.label_password.setObjectName("label_password")
        self.verticalLayout_2.addWidget(self.label_password)
        self.register_Password = QtWidgets.QLineEdit(PageRegister)
        self.register_Password.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    height: 40px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.register_Password.setObjectName("register_Password")
        self.verticalLayout_2.addWidget(self.register_Password)
        self.label_confirm_password = QtWidgets.QLabel(PageRegister)
        self.label_confirm_password.setObjectName("label_confirm_password")
        self.verticalLayout_2.addWidget(self.label_confirm_password)
        self.register_Confirm_Password = QtWidgets.QLineEdit(PageRegister)
        self.register_Confirm_Password.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    height: 40px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.register_Confirm_Password.setObjectName("register_Confirm_Password")
        self.verticalLayout_2.addWidget(self.register_Confirm_Password)
        self.register_email = QtWidgets.QLabel(PageRegister)
        self.register_email.setObjectName("register_email")
        self.verticalLayout_2.addWidget(self.register_email)
        self.register_Email = QtWidgets.QLineEdit(PageRegister)
        self.register_Email.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    height: 40px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.register_Email.setObjectName("register_Email")
        self.verticalLayout_2.addWidget(self.register_Email)
        self.label = QtWidgets.QLabel(PageRegister)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.register_Button = QtWidgets.QPushButton(PageRegister)
        self.register_Button.setStyleSheet("")
        self.register_Button.setObjectName("register_Button")
        self.verticalLayout_2.addWidget(self.register_Button)

        self.retranslateUi(PageRegister)
        QtCore.QMetaObject.connectSlotsByName(PageRegister)

    def retranslateUi(self, PageRegister):
        _translate = QtCore.QCoreApplication.translate
        PageRegister.setWindowTitle(_translate("PageRegister", "Form"))
        self.register_label.setText(_translate("PageRegister", "Registration"))
        self.label_username.setText(_translate("PageRegister", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">User</span></p></body></html>"))
        self.label_password.setText(_translate("PageRegister", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Password</span></p></body></html>"))
        self.label_confirm_password.setText(_translate("PageRegister", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Confirm Password</span></p></body></html>"))
        self.register_email.setText(_translate("PageRegister", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Email</span></p></body></html>"))
        self.register_Button.setText(_translate("PageRegister", "Register"))
