# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageFileTree(object):
    def setupUi(self, PageFileTree):
        PageFileTree.setObjectName("PageFileTree")
        PageFileTree.resize(634, 551)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PageFileTree.sizePolicy().hasHeightForWidth())
        PageFileTree.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageFileTree)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(PageFileTree)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.treeView_files = QtWidgets.QTreeView(PageFileTree)
        self.treeView_files.setStyleSheet("QTreeView {\n"
"    background-color: rgba(27, 29, 35, 200);\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    height: 40px;\n"
"    color: rgba(255, 255, 255, 200);\n"
"}\n"
"\n"
"QTreeView::branch {\n"
"    color: rgba(255, 255, 255, 200);\n"
"}\n"
"\n"
"QTreeView::branch:has-children{\n"
"    background-color: rgba(0,77,153, 200);\n"
"}\n"
"\n"
"QTreeView::branch:!has-children{\n"
"    background-color: rgba(0,100,0, 200);\n"
"}")
        self.treeView_files.setObjectName("treeView_files")
        self.verticalLayout.addWidget(self.treeView_files)
        self.button_searchImDb = QtWidgets.QPushButton(PageFileTree)
        self.button_searchImDb.setObjectName("button_searchImDb")
        self.verticalLayout.addWidget(self.button_searchImDb)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)

        self.retranslateUi(PageFileTree)
        QtCore.QMetaObject.connectSlotsByName(PageFileTree)

    def retranslateUi(self, PageFileTree):
        _translate = QtCore.QCoreApplication.translate
        PageFileTree.setWindowTitle(_translate("PageFileTree", "Form"))
        self.label_title.setText(_translate("PageFileTree", "File Browser"))
        self.button_searchImDb.setText(_translate("PageFileTree", "Search on imDb"))
