# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PagePlayer(object):
    def setupUi(self, PagePlayer):
        PagePlayer.setObjectName("PagePlayer")
        PagePlayer.resize(1040, 792)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PagePlayer.sizePolicy().hasHeightForWidth())
        PagePlayer.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PagePlayer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(PagePlayer)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.tabWidget = QtWidgets.QTabWidget(PagePlayer)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgba(27, 29, 35, 200);\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(44, 49, 60);\n"
"  border: 1px solid lightgray; \n"
"  padding: 15px;\n"
"  color:rgb(255, 255, 255);\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgba(27, 29, 35, 200);\n"
"  margin-bottom: -1px; \n"
"  color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_player = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_player.sizePolicy().hasHeightForWidth())
        self.tab_player.setSizePolicy(sizePolicy)
        self.tab_player.setObjectName("tab_player")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_player)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mediaplayer = QVideoWidget(self.tab_player)
        self.mediaplayer.setStyleSheet(" background: rgb(44, 49, 60);")
        self.mediaplayer.setObjectName("mediaplayer")
        self.verticalLayout.addWidget(self.mediaplayer)
        self.horizontalLayout_timeline = QtWidgets.QHBoxLayout()
        self.horizontalLayout_timeline.setObjectName("horizontalLayout_timeline")
        self.currentTimeLabel = QtWidgets.QLabel(self.tab_player)
        self.currentTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.currentTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.horizontalLayout_timeline.addWidget(self.currentTimeLabel)
        self.timeSlider = QtWidgets.QSlider(self.tab_player)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout_timeline.addWidget(self.timeSlider)
        self.totalTimeLabel = QtWidgets.QLabel(self.tab_player)
        self.totalTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.totalTimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.horizontalLayout_timeline.addWidget(self.totalTimeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_timeline)
        self.horizontalLayout_controls = QtWidgets.QHBoxLayout()
        self.horizontalLayout_controls.setObjectName("horizontalLayout_controls")
        self.previousButton = QtWidgets.QPushButton(self.tab_player)
        self.previousButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/16x16/icons/16x16/cil-media-skip-backward);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.previousButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("New folder (7)/fail/images/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_controls.addWidget(self.previousButton)
        self.playButton = QtWidgets.QPushButton(self.tab_player)
        self.playButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/16x16/icons/16x16/cil-media-play.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.playButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("New folder (7)/fail/images/control-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon1)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_controls.addWidget(self.playButton)
        self.pauseButton = QtWidgets.QPushButton(self.tab_player)
        self.pauseButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/16x16/icons/16x16/cil-media-pause);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.pauseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("New folder (7)/fail/images/control-stop-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon2)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_controls.addWidget(self.pauseButton)
        self.stopButton = QtWidgets.QPushButton(self.tab_player)
        self.stopButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/16x16/icons/16x16/cil-media-stop);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.stopButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("New folder (7)/fail/images/control-skip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_controls.addWidget(self.stopButton)
        self.nextButton = QtWidgets.QPushButton(self.tab_player)
        self.nextButton.setStyleSheet("QPushButton {\n"
"    background-image: url(:/16x16/icons/16x16/cil-media-skip-forward);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.nextButton.setText("")
        self.nextButton.setIcon(icon)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_controls.addWidget(self.nextButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_controls.addItem(spacerItem)
        self.label_mute = QtWidgets.QLabel(self.tab_player)
        self.label_mute.setMinimumSize(QtCore.QSize(32, 32))
        self.label_mute.setStyleSheet("\n"
"    background-image: url(:/16x16/icons/16x16/cil-volume-high);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"")
        self.label_mute.setText("")
        self.label_mute.setPixmap(QtGui.QPixmap("New folder (7)/fail/images/speaker-volume.png"))
        self.label_mute.setObjectName("label_mute")
        self.horizontalLayout_controls.addWidget(self.label_mute)
        self.volumeSlider = QtWidgets.QSlider(self.tab_player)
        self.volumeSlider.setStyleSheet("color: rgb(255, 85, 0);")
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_controls.addWidget(self.volumeSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_controls)
        self.verticalLayout.setStretch(0, 13)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.tabWidget.addTab(self.tab_player, "")
        self.tab_playlist = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab_playlist.sizePolicy().hasHeightForWidth())
        self.tab_playlist.setSizePolicy(sizePolicy)
        self.tab_playlist.setObjectName("tab_playlist")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_playlist)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listView_playlist = QtWidgets.QListView(self.tab_playlist)
        self.listView_playlist.setStyleSheet(" background: rgb(44, 49, 60);\n"
" color:rgb(255, 255, 255);")
        self.listView_playlist.setObjectName("listView_playlist")
        self.verticalLayout_3.addWidget(self.listView_playlist)
        self.addMediaButton = QtWidgets.QPushButton(self.tab_playlist)
        self.addMediaButton.setObjectName("addMediaButton")
        self.verticalLayout_3.addWidget(self.addMediaButton)
        self.tabWidget.addTab(self.tab_playlist, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(PagePlayer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PagePlayer)

    def retranslateUi(self, PagePlayer):
        _translate = QtCore.QCoreApplication.translate
        PagePlayer.setWindowTitle(_translate("PagePlayer", "Form"))
        self.label_title.setText(_translate("PagePlayer", "Video Player"))
        self.currentTimeLabel.setText(_translate("PagePlayer", "0:00"))
        self.totalTimeLabel.setText(_translate("PagePlayer", "0:00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_player), _translate("PagePlayer", "Player"))
        self.addMediaButton.setText(_translate("PagePlayer", "Add media"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_playlist), _translate("PagePlayer", "Playlist"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
