# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageData(object):
    def setupUi(self, PageData):
        PageData.setObjectName("PageData")
        PageData.resize(616, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PageData.sizePolicy().hasHeightForWidth())
        PageData.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PageData)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(PageData)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.tabWidget = QtWidgets.QTabWidget(PageData)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"   background: rgb(44, 49, 60);\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgba(27, 29, 35, 200);\n"
"  border: 1px solid lightgray; \n"
"  padding: 15px;\n"
"  color: rgb(255, 255, 255);\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgba(27, 29, 35, 200);\n"
"  margin-bottom: -1px; \n"
"  color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.data_tab = QtWidgets.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.data_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.data_layout = QtWidgets.QVBoxLayout()
        self.data_layout.setObjectName("data_layout")
        self.scrollArea = QtWidgets.QScrollArea(self.data_tab)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.data_widget = QtWidgets.QWidget()
        self.data_widget.setGeometry(QtCore.QRect(0, 0, 560, 352))
        self.data_widget.setObjectName("data_widget")
        self.scrollArea_layout = QtWidgets.QVBoxLayout(self.data_widget)
        self.scrollArea_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.scrollArea_layout.setObjectName("scrollArea_layout")
        self.scrollArea.setWidget(self.data_widget)
        self.data_layout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.data_layout)
        self.tabWidget.addTab(self.data_tab, "")
        self.input_tab = QtWidgets.QWidget()
        self.input_tab.setObjectName("input_tab")
        self.data_title = QtWidgets.QLineEdit(self.input_tab)
        self.data_title.setGeometry(QtCore.QRect(20, 40, 381, 21))
        self.data_title.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.data_title.setObjectName("data_title")
        self.data_date = QtWidgets.QDateEdit(self.input_tab)
        self.data_date.setGeometry(QtCore.QRect(20, 90, 381, 22))
        self.data_date.setStyleSheet("\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    height: 40px;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.data_date.setObjectName("data_date")
        self.data_review = QtWidgets.QLineEdit(self.input_tab)
        self.data_review.setGeometry(QtCore.QRect(20, 150, 381, 161))
        self.data_review.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.data_review.setObjectName("data_review")
        self.data_title_label = QtWidgets.QLabel(self.input_tab)
        self.data_title_label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.data_title_label.setObjectName("data_title_label")
        self.data_date_label = QtWidgets.QLabel(self.input_tab)
        self.data_date_label.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.data_date_label.setObjectName("data_date_label")
        self.data_review_label = QtWidgets.QLabel(self.input_tab)
        self.data_review_label.setGeometry(QtCore.QRect(20, 130, 47, 13))
        self.data_review_label.setObjectName("data_review_label")
        self.confirm_Button = QtWidgets.QPushButton(self.input_tab)
        self.confirm_Button.setGeometry(QtCore.QRect(20, 330, 80, 21))
        self.confirm_Button.setObjectName("confirm_Button")
        self.tabWidget.addTab(self.input_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(PageData)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PageData)

    def retranslateUi(self, PageData):
        _translate = QtCore.QCoreApplication.translate
        PageData.setWindowTitle(_translate("PageData", "Form"))
        self.label_title.setText(_translate("PageData", "Film reviews"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_tab), _translate("PageData", "Review"))
        self.data_title_label.setText(_translate("PageData", "Film Title"))
        self.data_date_label.setText(_translate("PageData", "Review Date"))
        self.data_review_label.setText(_translate("PageData", "Review"))
        self.confirm_Button.setText(_translate("PageData", "Confirm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_tab), _translate("PageData", "New Review"))
