# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageHome(object):
    def setupUi(self, PageHome):
        PageHome.setObjectName("PageHome")
        PageHome.resize(616, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PageHome.sizePolicy().hasHeightForWidth())
        PageHome.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PageHome)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(PageHome)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(PageHome)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(PageHome)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonLogout = QtWidgets.QPushButton(PageHome)
        self.buttonLogout.setObjectName("buttonLogout")
        self.verticalLayout_3.addWidget(self.buttonLogout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(0, 15)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(1, 7)

        self.retranslateUi(PageHome)
        QtCore.QMetaObject.connectSlotsByName(PageHome)

    def retranslateUi(self, PageHome):
        _translate = QtCore.QCoreApplication.translate
        PageHome.setWindowTitle(_translate("PageHome", "Form"))
        self.label_title.setText(_translate("PageHome", "Home"))
        self.label_2.setText(_translate("PageHome", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Media Player V 1.0.0.</span></p><p><span style=\" font-size:12pt; color:#ffffff;\">Feature List:</span></p><p><span style=\" color:#ffffff;\">- </span><span style=\" font-size:10pt; color:#ffffff;\">Media player: You can add multiple elements to a playlist using the File Tree Browser or <br/>you can manualy add elements using the Open File dialog </span></p><p><span style=\" font-size:10pt; color:#ffffff;\">- File Tree Browser: Lists local media files, double clicking an element adds it to the playlist, <br/>search on imdb button looks up the name of the file on imdb</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">- Film Reviews: You can leave a review about a film you viewed which will be visible to other users</span></p><p><span style=\" color:#ffffff;\">- </span><span style=\" font-size:10pt; color:#ffffff;\">Film Lookup: Using this feature you can look up a film which you saw in another users review, <br/>or by just simply searching for a film title</span></p><p><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.label.setText(_translate("PageHome", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Change log:</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">- Added an option to doubleclick files in File Tree Browser which adds the element to the playlist</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">- Added an option to edit or remove your own reviews in Film Reviews<br/></span></p><p><span style=\" font-size:10pt; color:#ffffff;\">- Hidden the Registration and Login page when a user is already logged in</span></p></body></html>"))
        self.buttonLogout.setText(_translate("PageHome", "Logout"))
