# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_imdb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PageImdb(object):
    def setupUi(self, PageImdb):
        PageImdb.setObjectName("PageImdb")
        PageImdb.resize(616, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PageImdb.sizePolicy().hasHeightForWidth())
        PageImdb.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageImdb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_title = QtWidgets.QLabel(PageImdb)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        self.lineEdit_search = QtWidgets.QLineEdit(PageImdb)
        self.lineEdit_search.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"    height: 25px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.button_search = QtWidgets.QPushButton(PageImdb)
        self.button_search.setObjectName("button_search")
        self.horizontalLayout.addWidget(self.button_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(PageImdb)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.data_widget = QtWidgets.QWidget()
        self.data_widget.setGeometry(QtCore.QRect(0, 0, 582, 424))
        self.data_widget.setObjectName("data_widget")
        self.scrollArea_layout = QtWidgets.QVBoxLayout(self.data_widget)
        self.scrollArea_layout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.scrollArea_layout.setObjectName("scrollArea_layout")
        self.scrollArea.setWidget(self.data_widget)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(PageImdb)
        QtCore.QMetaObject.connectSlotsByName(PageImdb)

    def retranslateUi(self, PageImdb):
        _translate = QtCore.QCoreApplication.translate
        PageImdb.setWindowTitle(_translate("PageImdb", "Form"))
        self.label_title.setText(_translate("PageImdb", "IMDB"))
        self.button_search.setText(_translate("PageImdb", "Search"))
